name: CI exemplo

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Comando
        run: |
          Write-Host "teste"
